on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Pesho
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: pwd
        run: pwd
      - name: df
        run: df
      - name: ls
        run: ls -la
