env: 
  aws_region: us-east-1 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Pesho
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:  ${{ secrets.aws_access_key_id }}
          aws-secret-access-key:  ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ env.aws_region }}
      - name: pwd
        run: pwd
      - name: df
        run: df
      - name: ls
        run: ls -la
      - name: Describe regions
        run: aws ec2 describe-regions
