on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
name: Pesho
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: w
        run: w
      - name: df
        run: df
      - name: ls
        run: ls -la
